Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UpFit__main.Models;

namespace UpFit__main.Controllers
{
    public class AdminsController : Controller
    {
        private CodeFirstDb db = new CodeFirstDb();

        // GET: Admins
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult ManageAdmins()
        {
            return View(db.admins.ToList());
        }

        public ActionResult ManageFoods()
        {
            //return View(db.foods.ToList());
            IEnumerable<Food> foods = db.foods.ToList();
            IEnumerable<FoodType> foodTypes = db.foodTypes.ToList();

            ViewBag.FoodTypes = foodTypes;

            return View(foods);
        }

        public ActionResult ManageFoodTypes()
        {
            return View(db.foodTypes.ToList());
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            using (CodeFirstDb db = new CodeFirstDb())
            {
                var adm = db.admins.SingleOrDefault(u => u.UserName == admin.UserName && u.Password == admin.Password);
                if (adm != null)
                {
                    Session["UserID"] = adm.AdminID.ToString();
                    Session["UserName"] = adm.UserName.ToString();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password.");
                }
            }
            return View();
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdminID,UserName,Password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //****************************EDIT-ADMIN****************************************88
        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdminID, UserName, Password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.admins.Find(id);
            db.admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admins/ManageUsers
        public ActionResult ManageUsers()
        {
            return View(db.users.ToList());
        }

        // GET: Admins/AddUser
        public ActionResult AddUser()
        {
            return View();
        }

        // POST: Admins/AddUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUser(User user)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(user);
                db.SaveChanges();
                return RedirectToAction("ManageUsers");
            }

            return View(user);
        }


        // GET: Admins/DeleteUser/5
        public ActionResult DeleteUser(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admins/DeleteUser/5
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUserConfirmed(int id)
        {
            User user = db.users.Find(id);
            db.users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("ManageUsers");
        }

        //*****************************************************************************************


        // GET: Admins/AddFood
        public ActionResult CreateFoods()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFoods(Food food)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the selected food type from the database
                var foodType = db.foodTypes.FirstOrDefault(ft => ft.ID_Type == food.type);
                if (foodType != null)
                {
                    // Associate the food type with the food entity
                    food.type = foodType.ID_Type;

                    db.foods.Add(food);
                    db.SaveChanges();
                    return RedirectToAction("ManageFoods");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid food type.");
                }
            }

            // Retrieve the list of food types to display in the view
            ViewBag.FoodTypes = db.foodTypes.ToList();

            return View(food);
        }


        // GET: Admins/EditFood/5
        public ActionResult EditFoods(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // POST: Admins/EditFood/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFoods(Food food)
        {
            if (ModelState.IsValid)
            {
                db.Entry(food).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageFoods");
            }
            return View(food);
        }

        // POST: Admins/DeleteFood/5
        [HttpPost, ActionName("DeleteFood")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFoodsConfirmed(int id)
        {
            Food food = db.foods.Find(id);
            db.foods.Remove(food);
            db.SaveChanges();
            return RedirectToAction("ManageFoods");
        }

        // GET: Admins/AddFoodType
        public ActionResult CreateFoodTypes()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFoodTypes(FoodType foodType)
        {
            if (ModelState.IsValid)
            {
                db.foodTypes.Add(foodType);
                db.SaveChanges();
                return RedirectToAction("ManageFoodTypes");
            }

            return View(foodType);
        }


        // GET: Admins/EditFoodType/5
        public ActionResult EditFoodTypes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FoodType foodType = db.foodTypes.Find(id);
            if (foodType == null)
            {
                return HttpNotFound();
            }
            return View(foodType);
        }

        // POST: Admins/EditFoodType/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFoodTypes(FoodType foodType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(foodType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageFoodTypes");
            }
            return View(foodType);
        }

        // POST: Admins/DeleteFoodType/5
        [HttpPost, ActionName("DeleteFoodType")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFoodTypesConfirmed(int id)
        {
            FoodType foodType = db.foodTypes.Find(id);
            db.foodTypes.Remove(foodType);
            db.SaveChanges();
            return RedirectToAction("ManageFoodTypes");
        }

        // more actions * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

        // GET: Admins/DeleteFood/5
        public ActionResult DeleteFoods(int? id)
        {
            if (id == null)
            {

Views/Admins/AddUser.cshtml
@model UpFit__main.Models.User
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "AddUser";
}

<h2>Add User</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubscriptionTypeFK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubscriptionTypeFK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubscriptionTypeFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KcalDaily, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KcalDaily, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KcalDaily, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ManageUsers")
</div>

Views/Admins/CreateFoodTypes.cshtml
@model UpFit__main.Models.FoodType
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FoodType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ManageFoodTypes")
</div>

Views/Admins/Delete.cshtml
@model UpFit__main.Models.Admin
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Admins/DeleteFoodTypes.cshtml
@model UpFit__main.Models.FoodType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FoodType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Admins/DeleteFoods.cshtml
@model UpFit__main.Models.Food

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Delete";
}


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Food</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proteins)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proteins)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.carbs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carbs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fibers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fibers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vitamin_A)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vitamin_A)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vitamin_B)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vitamin_B)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vitamin_C)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vitamin_C)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vitamin_D)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vitamin_D)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vitamin_E)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vitamin_E)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Admins/DeleteUser.cshtml
@model UpFit__main.Models.User
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "DeleteUser";
}

<main>
    <h2>Delete User</h2>

    <h3>Are you sure you want to delete this user?</h3>
    <div class="d-flex justify-content-center align-items-center flex-column" style="background-color: rgba(255,255,255,0.3); ">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SubscriptionTypeFK)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubscriptionTypeFK)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Age)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Age)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Height)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Height)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Weight)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Weight)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.KcalDaily)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.KcalDaily)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "ManageUsers")
            </div>
        }
    </div>
</main>

Views/Admins/DetailsFoodTypes.cshtml
@model UpFit__main.Models.FoodType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>FoodType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Type }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Admins/Index.cshtml
@model IEnumerable<UpFit__main.Models.Admin>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    ViewBag.Title = "Index";
}
<div style="text-align: center;">
    <img src="~/Content/LOGO.png" alt="logo" width="20%" height="auto">
    <h2>Logged In as Admin</h2>
    <p>Welcome to your admin account! Select the operation you want to perform!</p>

    <div style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
        @Html.ActionLink("Home", "Index", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

        @Html.ActionLink("Manage Users", "ManageUsers", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

        @Html.ActionLink("Manage Admins", "ManageAdmins", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

        @Html.ActionLink("Manage Foods", "ManageFoods", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

        @Html.ActionLink("Manage Food Types", "ManageFoodTypes", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

        @Html.ActionLink("Log Out", "Index", "Home", new { area = "" }, new { @class = "btn btn-primary btn-custom" })
    </div>
</div>

<style>
    .btn-custom {
        padding: 10px 20px;
        width: 200px;
        margin-bottom: 10px;
    }
</style>

Views/Admins/ManageAdmins.cshtml
@model IEnumerable<UpFit__main.Models.Admin>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    ViewBag.Title = "ManageAdmins";
}

<h2>Manage Admins</h2>

@Html.ActionLink("Back", "Index", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

@Html.ActionLink("Create New", "Create", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.AdminID })
            </td>
        </tr>
    }

</table>

Views/Admins/ManageFoodTypes.cshtml
@model IEnumerable<UpFit__main.Models.FoodType>
@{
    ViewBag.Title = "ManageFoodTypes";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Manage Food Types</h2>

@Html.ActionLink("Back", "Index", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

@Html.ActionLink("Create New", "CreateFoodTypes", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditFoodTypes", new { id = item.ID_Type }) |
                @Html.ActionLink("Delete", "DeleteFoodTypes", new { id = item.ID_Type })
            </td>
        </tr>
    }

</table>

Views/Admins/ManageFoods.cshtml
@model IEnumerable<UpFit__main.Models.Food>
@{
    ViewBag.Title = "ManageFoods";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using UpFit__main.Models;

<h2>Manage Foods</h2>

@Html.ActionLink("Back", "Index", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

@Html.ActionLink("Create New", "CreateFoods", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        FoodType foodType = null;
        foreach (var type in ViewBag.FoodTypes)
        {
            if (type.ID_Type == item.type)
            {
                foodType = type;
                break;
            }
        }

        <tr>
            <td>
                @if (foodType != null)
                {
                    @foodType.Name
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditFoods", new { id = item.foodID }) |
                @Html.ActionLink("Delete", "DeleteFoods", new { id = item.foodID })
            </td>
        </tr>
    }


</table>

Views/Admins/ManageUsers.cshtml
@model IEnumerable<UpFit__main.Models.User>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    ViewBag.Title = "ManageUsers";
}

<h2>Manage Users</h2>

@Html.ActionLink("Back", "Index", "Admins", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

@Html.ActionLink("Create New", "AddUser", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubscriptionTypeFK)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SubscriptionTypeFK)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>

            <td>
                @Html.ActionLink("Delete", "DeleteUser", new { id = item.UserID }) |
                @Html.ActionLink("Details", "DetailsUser", new { id = item.UserID })
            </td>
        </tr>
    }

</table>