Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UpFit__main.Models
{
    public class User
    {
        [Key]
        public int UserID { get; set; }

        [Required(ErrorMessage = "Subscription Type is required.")]
        [DisplayName("Subscription Type")]
        public int SubscriptionTypeFK { get; set; }

        [Required(ErrorMessage = "Username is required.")]
        [RegularExpression(@"^[a-zA-Z0-9_]+$", ErrorMessage = "Username can only contain letters, numbers, and underscores.")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required.")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string Password { get; set; }

        [Required(ErrorMessage = "First Name is required.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First Name can only contain letters.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Last Name can only contain letters.")]
        public string LastName { get; set; }

        [RegularExpression("^[FM]$", ErrorMessage = "Gender must be 'F' or 'M'.")]
        [Required(ErrorMessage = "Gender is required.")]
        public string Gender { get; set; }

        [Range(1, 150, ErrorMessage = "Age must be between 1 and 150.")]
        public int Age { get; set; }

        [Range(50, 300, ErrorMessage = "Height must be between 50 and 300.")]
        public int Height { get; set; }

        [Range(10, 300, ErrorMessage = "Weight must be between 10 and 300.")]
        public int Weight { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Kcal Daily must be a positive value.")]
        public int KcalDaily { get; set; }
 
        public double Lifestyle { get; set; }
    }
}

Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using UpFit__main.Models;

namespace UpFit__main.Controllers
{
    public class MealsController : Controller
    {
        private CodeFirstDb db = new CodeFirstDb();

        // GET: Meals
        public ActionResult Index()
        {
            return View(db.meals.ToList());
        }

        // GET: Meals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }


        // GET: Meals/Create
        public ActionResult Create()
        {
           ViewBag.FoodFK = new SelectList(db.foods, "foodID", "name");
            return View();
        }

        // POST: Meals/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "mealID,mealTypeFK,userFK,foodFK,quantity,date")] Meal meal)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        meal.date = DateTime.Today; // Set today's date
        //        db.meals.Add(meal);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
            
        //    ViewBag.MealTypeFK = new SelectList(db.foodTypes, "ID_Type", "Name", meal.mealTypeFK);
        //    ViewBag.FoodFK = new SelectList(db.foods, "foodID", "name", meal.foodFK);
        //    return View(meal);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mealID,mealTypeFK,userFK,foodFK,quantity,date")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                meal.date = DateTime.Today; // Set today's date
                db.meals.Add(meal);
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            ViewBag.FoodFK = new SelectList(db.foods, "foodID", "name",meal.foodFK);

            return View(meal);
        }
        // GET: Meals/Edit/5
        public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Meal meal = db.meals.Find(id);
                if (meal == null)
                {
                    return HttpNotFound();
                }
                return View(meal);
            }

            // POST: Meals/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "mealID,mealTypeFK,userFK,foodFK,quantity")] Meal meal)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(meal).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(meal);
            }

            // GET: Meals/Delete/5
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Meal meal = db.meals.Find(id);
                if (meal == null)
                {
                    return HttpNotFound();
                }
                return View(meal);
            }

            // POST: Meals/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public ActionResult DeleteConfirmed(int id)
            {
                Meal meal = db.meals.Find(id);
                db.meals.Remove(meal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
    }
}

Controllers/UsersController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UpFit__main.Models;

namespace UpFit__main.Controllers
{
    public class UsersController : Controller
    {
        private CodeFirstDb db = new CodeFirstDb();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.users.ToList());
        }


        public ActionResult AddDetails()
        {
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            using (CodeFirstDb db = new CodeFirstDb())
            {
                var usr = db.users.SingleOrDefault(u => u.UserName == user.UserName && u.Password == user.Password);
                if (usr != null)
                {
                    Session["UserID"] = usr.UserID.ToString();
                    Session["UserName"] = usr.UserName.ToString();
                    Session["SubscriptionType"] = usr.SubscriptionTypeFK.ToString();
                    Session["KcalDaily"] = usr.KcalDaily;
                    return RedirectToAction("LoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password.");
                }
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["UserID"] != null)
            {
                int userId = Convert.ToInt32(Session["UserID"]);
                MacroCalculations(userId);
                // Retrieve the user from the database based on the UserID
                User user = db.users.Find(userId);
         
                if (user != null)
                {
                    return View(user);
                }
            }

            // If the user is not logged in or not found in the database, redirect to the login page
            return RedirectToAction("Login");
        }

        // LoginRegistration
        // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        // UpFit!-main

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Register
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult ViewAccounts()
        {
            return View();
        }

        // POST: Users/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "UserID,SubscriptionTypeFK,UserName,Password,FirstName,LastName,Gender,Age,Height,Weight,KcalDaily,Lifestyle")] User user)
        {
            if (user.Gender == "M")
            {
                user.KcalDaily = (int)Math.Round(user.Lifestyle * (66 + (13.7 * user.Weight) + (5 * user.Height) - (6.8 * user.Age)));
            }
            else
            {
                user.KcalDaily = (int)Math.Round(user.Lifestyle * (65 + (9.5 * user.Weight) + (1.8 * user.Height) - (4.7 * user.Age)));
            }
            if (ModelState.IsValid)
            {
                db.users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,SubscriptionTypeFK,UserName,Password,FirstName,LastName,Gender,Age,Height,Weight,KcalDaily")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.users.Find(id);
            db.users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult VideoList()
        {
            using (CodeFirstDb db = new CodeFirstDb())
            {
                List<Video> Videolist = new List<Video>();
                foreach (Video video in db.videos)
                {
                    Video dbVideo = new Video();
                    {
                        dbVideo.Vname = video.Vname;
                        dbVideo.Vpath = video.Vpath.ToString();
                    };
                    Videolist.Add(dbVideo);
                }
                return View(Videolist);
            }
        }

        [HttpGet]
        public List<double> MacroCalculations(int userID)
        {
            DateTime day = DateTime.Today;
            double calories = 0;
            double carbo = 0.00, proteins = 0.00, fats = 0.00, fibers = 0.00, vitamin_A = 0.00, vitamin_B = 0.00, vitamin_C = 0, vitamin_D = 0, vitamin_E = 0;
            List<double> totalmacro = new List<double>();
            using (CodeFirstDb db = new CodeFirstDb())
            {
                foreach (Meal meal in db.meals)
                {
                    if (meal.userFK == userID)
                    {
                        if(meal.date == day)
                        {
                            Food aliment = db.foods.SingleOrDefault(x => x.foodID == meal.foodFK);
                            calories = calories + (aliment.calories)*meal.quantity/100;
                            carbo = carbo + (double)aliment.carbs*meal.quantity/100;
                            proteins = proteins + (double)aliment.proteins* meal.quantity/100;
                            fats=fats+ (double)aliment.fats * meal.quantity / 100;
                            fibers=fibers +(double)aliment.fibers * meal.quantity / 100;
                            vitamin_A = vitamin_A + (double)aliment.vitamin_A * meal.quantity / 100;
                            vitamin_B = vitamin_B + (double)aliment.vitamin_B * meal.quantity / 100;
                            vitamin_C = vitamin_C + (double)aliment.vitamin_C * meal.quantity / 100;
                            vitamin_D = vitamin_D + (double)aliment.vitamin_D * meal.quantity / 100;
                            vitamin_E = vitamin_E + (double)aliment.vitamin_E * meal.quantity / 100; 
                        }
                    }
                }
                totalmacro.AddRange(new double[] { calories, carbo, proteins, fats, fibers, vitamin_A, vitamin_B, vitamin_C, vitamin_D, vitamin_E });
                ViewBag.MacroDaily = totalmacro;
            }
            return totalmacro;
        }
    }
}

Views/Users/Delete.cshtml
@model UpFit__main.Models.User
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubscriptionTypeFK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubscriptionTypeFK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KcalDaily)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KcalDaily)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Users/Details.cshtml
@model UpFit__main.Models.User
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubscriptionTypeFK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubscriptionTypeFK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KcalDaily)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KcalDaily)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Users/Index.cshtml
@model IEnumerable<UpFit__main.Models.User>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Register New", "Register")
</p>
<div class="d-flex justify-content-center align-items-center flex-column" style="background-color: rgba(255,255,255,0.3); ">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SubscriptionTypeFK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KcalDaily)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SubscriptionTypeFK)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KcalDaily)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.UserID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.UserID })
                </td>
            </tr>
        }

    </table>
</div>

Views/Users/LoggedIn.cshtml
@model UpFit__main.Models.User
@{
    ViewBag.Title = "LoggedIn";
    var alo = Session["SubscriptionType"].ToString();
    var userID = Session["UserID"].ToString();
    var kcaldaily = Session["KcalDaily"];
}


@using (Html.BeginForm("MacroCalculations"))
{
    List<double> macrodaily = ViewBag.Macrodaily;
    var remainedKcal = (int)kcaldaily - (int)Math.Round(macrodaily[0]);
    if (alo == "0")
    {
        @Html.Partial("_NavBarBasic")


        @Html.AntiForgeryToken()
        <div class="d-flex justify-content-center align-items-center flex-column" style="background-color: rgba(255,255,255,0.3); ">
            <h2> Hello, @Model.FirstName </h2>
            <div>
                <p>
                    Based on your info we calculated your daily necessary intake for maintenance.
                </p>
                <p>
                    Your goal should be: @kcaldaily kcal
                </p>
                <p>
                    You have left: @remainedKcal kcal
                </p>
            </div>
            <div style="display: flex; flex-direction: column; align-items: center; justify-content: center;">

                @Html.ActionLink("Add Meal", "Create", "Meals", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

                <div>
                    <div style="height: 80vh; ">

                        <div class="row">
                            <div class="col-md-12">

                                <h1 class="text-center my-4">My Daily Nutrients</h1>
                            </div>
                        </div>

                        <div class="row d-flex justify-content-center">
                            <div class="col-md-12">
                                <div class="card-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Total Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories consumed</td>
                                                <td> @macrodaily[0] </td>

                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td> @macrodaily[2] </td>

                                            </tr>
                                            <tr>
                                                <td>Carbohydrates</td>
                                                <td>@macrodaily[1].ToString()</td>
                                            </tr>
                                            <tr>
                                                <td>Fats</td>
                                                <td>@macrodaily[3].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Fiber</td>
                                                <td>@macrodaily[4].ToString()</td>

                                            </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    else
    {
        @Html.Partial("_NavBarPremium")
        @Html.AntiForgeryToken()
        <div class="d-flex justify-content-center align-items-center flex-column" style="background-color: rgba(255,255,255,0.3); ">
            <h2> Hello, @Model.FirstName </h2>
            <div>
                <p>
                    Based on your info we calculated your daily necessary intake for maintenance.
                </p>
                <p>
                    Your goal should be: @kcaldaily kcal
                </p>
                <p>
                    You have left: @remainedKcal kcal
                </p>
            </div>
            <div style="display: flex; flex-direction: column; align-items: center; justify-content: center;">

                @Html.ActionLink("Add Meal", "Create", "Meals", new { area = "" }, new { @class = "btn btn-primary btn-custom" })

                <div>
                    <div style="height: 120vh;">

                        <div class="row">
                            <div class="col-md-12">

                                <h1 class="text-center my-4">My Daily Nutrients</h1>
                            </div>
                        </div>

                        <div class="row d-flex justify-content-center">
                            <div class="col-md-12">
                                <div class="card-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Total Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories consumed</td>
                                                <td> @macrodaily[0] </td>

                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td> @macrodaily[2] </td>

                                            </tr>
                                            <tr>
                                                <td>Carbohydrates</td>
                                                <td>@macrodaily[1].ToString()</td>
                                            </tr>
                                            <tr>
                                                <td>Fats</td>
                                                <td>@macrodaily[3].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Fiber</td>
                                                <td>@macrodaily[4].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Vitamin A</td>
                                                <td>@macrodaily[5].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Vitamin B</td>
                                                <td>@macrodaily[6].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Vitamin C</td>
                                                <td>@macrodaily[7].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Vitamin D</td>
                                                <td>@macrodaily[8].ToString()</td>

                                            </tr>
                                            <tr>
                                                <td>Vitamin E</td>
                                                <td>@macrodaily[9].ToString()</td>

                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Users/VideoList.cshtml
@{
    ViewBag.Title = "VideoList";
}

<h2>VideoList</h2>
<!DOCTYPE html>
<html>
<body>
    <div class="container">
        @using (Html.BeginForm("VideoList", "Users"))
        {
            foreach (var item in Model)
            {
                <div class="title" style="width:250px;"> @item.Vname </div>
                <div class="video-frame">
                    <video style="width:250px; height:155px;" controls>
                        <source src="@Url.Content(item.Vpath)" type="video/mp4" />
                    </video>
                </div>
            }
        }
    </div>
</body>
</html>

Views/Users/ViewAccounts.cshtml
@model IEnumerable<UpFit__main.Models.User>
@{
    ViewBag.Title = "ViewAccounts";
}

<h2>ViewAccounts</h2>